// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int PlayerCursor_94a5ba242d36ffd449a774ea4e84f0b5Index = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "PlayerCursor_94a5ba242d36ffd449a774ea4e84f0b5", 0 },

		};
	}
}
