// Copyright (c) coherence ApS.
// See the license file in the project root for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Toolkit;
	using UnityEngine;
	using Unity.Collections;
	using Unity.Mathematics;

	public struct PlayerCursor_Player : ICoherenceComponentData
	{
		public string playerName;
		public long startOnFrame;
		public int ping;
		public float fps;

		public override string ToString()
		{
			return $"PlayerCursor_Player(playerName: {playerName}, startOnFrame: {startOnFrame}, ping: {ping}, fps: {fps})";
		}

		public uint GetComponentType() => Definition.InternalPlayerCursor_Player;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;

		private static readonly int _ping_Min = -9999;
		private static readonly int _ping_Max = 9999;
		private static readonly float _fps_Min = -2400f;
		private static readonly float _fps_Max = 2400f;
		private static readonly float _fps_Epsilon = 0.000286102294921875f;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (PlayerCursor_Player)data;
			if ((mask & 0x01) != 0)
			{
				playerName = other.playerName;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				startOnFrame = other.startOnFrame;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				ping = other.ping;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				fps = other.fps;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			uint mask = 0;
			var newData = (PlayerCursor_Player)data;

			if (playerName.DiffersFrom(newData.playerName)) {
				mask |= 0b00000000000000000000000000000001;
			}
			if (startOnFrame != newData.startOnFrame) {
				mask |= 0b00000000000000000000000000000010;
			}
			if (ping != newData.ping) {
				mask |= 0b00000000000000000000000000000100;
			}
			if (fps.DiffersFrom(newData.fps, _fps_Epsilon)) {
				mask |= 0b00000000000000000000000000001000;
			}

			return mask;
		}

		public static void Serialize(PlayerCursor_Player data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteShortString(data.playerName);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteInt64(data.startOnFrame);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.ping, _ping_Min, _ping_Max, "PlayerCursor_Player.ping");

				bitStream.WriteIntegerRange(data.ping, 15, -9999);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.fps, _fps_Min, _fps_Max, "PlayerCursor_Player.fps");

				bitStream.WriteFixedPoint(CoherenceToUnityConverters.FromUnityfloat(data.fps), 24, 2400);
			}
			mask >>= 1;
		}

		public static (PlayerCursor_Player, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new PlayerCursor_Player();
			if (bitStream.ReadMask())
			{
				val.playerName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.startOnFrame = bitStream.ReadInt64();
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.ping = bitStream.ReadIntegerRange(15, -9999);
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.fps = CoherenceToUnityConverters.ToUnityfloat(bitStream.ReadFixedPoint(24, 2400));
				mask |= 0b00000000000000000000000000001000;
			}
			return (val, mask, null);
		}
	}
}