// Copyright (c) coherence ApS.
// See the license file in the project root for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Toolkit;
	using UnityEngine;
	using Unity.Collections;
	using Unity.Mathematics;

	public struct PlayerCursor_Player : ICoherenceComponentData
	{
		public FixedString64 playerName;
		public long startOnFrame;

		public override string ToString()
		{
			return $"PlayerCursor_Player(playerName: {playerName}, startOnFrame: {startOnFrame})";
		}

		public uint GetComponentType() => Definition.InternalPlayerCursor_Player;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;


		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (PlayerCursor_Player)data;
			if ((mask & 0x01) != 0)
			{
				playerName = other.playerName;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				startOnFrame = other.startOnFrame;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			uint mask = 0;
			var newData = (PlayerCursor_Player)data;

			if (playerName.DiffersFrom(newData.playerName)) {
				mask |= 0b00000000000000000000000000000001;
			}
			if (startOnFrame != newData.startOnFrame) {
				mask |= 0b00000000000000000000000000000010;
			}

			return mask;
		}

		public static void Serialize(PlayerCursor_Player data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteShortString(CoherenceToUnityConverters.FromUnityFixedString64(data.playerName));
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteInt64(data.startOnFrame);
			}
			mask >>= 1;
		}

		public static (PlayerCursor_Player, uint, uint) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new PlayerCursor_Player();
			if (bitStream.ReadMask())
			{
				val.playerName = CoherenceToUnityConverters.ToUnityFixedString64(bitStream.ReadShortString());
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.startOnFrame = bitStream.ReadInt64();
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask, 0);
		}
	}
}