// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct PlayerCursor_Player_694873017490517114 : ICoherenceComponentData
	{
		public string playerName;
		public long startOnFrame;

		public override string ToString()
		{
			return $"PlayerCursor_Player_694873017490517114(playerName: {playerName}, startOnFrame: {startOnFrame})";
		}

		public uint GetComponentType() => Definition.InternalPlayerCursor_Player_694873017490517114;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;


		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (PlayerCursor_Player_694873017490517114)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				playerName = other.playerName;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				startOnFrame = other.startOnFrame;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			uint mask = 0;
			var newData = (PlayerCursor_Player_694873017490517114)data;

			if (playerName.DiffersFrom(newData.playerName)) {
				mask |= 0b00000000000000000000000000000001;
			}
			if (startOnFrame != newData.startOnFrame) {
				mask |= 0b00000000000000000000000000000010;
			}

			return mask;
		}

		public static void Serialize(PlayerCursor_Player_694873017490517114 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteShortString(data.playerName);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteLong(data.startOnFrame);
			}
			mask >>= 1;
		}

		public static (PlayerCursor_Player_694873017490517114, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new PlayerCursor_Player_694873017490517114();
			if (bitStream.ReadMask())
			{
				val.playerName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.startOnFrame = bitStream.ReadLong();
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask, null);
		}

		public static (PlayerCursor_Player_694873017490517114, uint, uint?) DeserializeArchetypePlayerCursor_94a5ba242d36ffd449a774ea4e84f0b5_PlayerCursor_Player_694873017490517114_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new PlayerCursor_Player_694873017490517114();
			if (bitStream.ReadMask())
			{
				val.playerName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.startOnFrame = bitStream.ReadLong();
				mask |= 0b00000000000000000000000000000010;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as PlayerCursor_Player_694873017490517114?;
		}
	}
}