// Copyright (c) coherence ApS.
// See the license file in the project root for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct WorldPositionQuery : ICoherenceComponentData
	{
		public Vector3 position;
		public float radius;

		public override string ToString()
		{
			return $"WorldPositionQuery(position: {position}, radius: {radius})";
		}

		public uint GetComponentType() => Definition.InternalWorldPositionQuery;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;

		private static readonly float _position_Epsilon = 2.3283064365386963e-10f;
		private static readonly float _radius_Epsilon = 2.3283064365386963e-10f;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (WorldPositionQuery)data;
			if ((mask & 0x01) != 0)
			{
				position = other.position;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				radius = other.radius;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			uint mask = 0;
			var newData = (WorldPositionQuery)data;

			if (position.DiffersFrom(newData.position, _position_Epsilon)) {
				mask |= 0b00000000000000000000000000000001;
			}
			if (radius.DiffersFrom(newData.radius, _radius_Epsilon)) {
				mask |= 0b00000000000000000000000000000010;
			}

			return mask;
		}

		public static void Serialize(WorldPositionQuery data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteVector3((data.position.ToCoreVector3()), FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.radius, FloatMeta.NoCompression());
			}
			mask >>= 1;
		}

		public static (WorldPositionQuery, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPositionQuery();
			if (bitStream.ReadMask())
			{
				val.position = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.radius = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask, null);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as WorldPositionQuery?;
		}
	}
}